---
- name: Add repository of fish
  become: yes
  apt_repository: repo=ppa:fish-shell/release-2

- name: Install fish from apt
  become: yes
  apt: name=fish state=latest

- name: Remove the fish directory
  file: path="{{ ansible_env.HOME }}"/.config/fish/ state=absent

- name: Checkout config files from github
  git:
    repo: https://github.com/NomadBlacky/fish-config.git
    dest: "{{ ansible_env.HOME }}/.config/fish"
