---
- name: Add repository of fish
  become: yes
  apt_repository: repo=ppa:fish-shell/release-2

- name: Install fish from apt
  become: yes
  apt: name=fish state=latest

- name: Remove the fish directory
  file: path="{{ HOME_DIR }}"/.config/fish/ state=absent

- name: Checkout config files from github
  git:
    repo: git@github.com:NomadBlacky/fish-config.git
    dest: "{{ HOME_DIR }}/.config/fish"
    accept_hostkey: yes
    key_file: "{{ HOME_DIR }}/.ssh/id_rsa"
