---
- hosts: localhost

  vars:
    BASHRC: "{{HOME_DIR}}/.bashrc"
    CONFIG_FISH: "{{HOME_DIR}}/.config/fish/config.fish"
  
  tasks:
    - name: Install dependency packages
      apt: name={{item}} state=latest
      with_items:
        - build-essential
        - libncurses-dev
        - autoconf
        - automake
        - autogen
        - git
        - texinfo
        - libtool
        - libgtk2.0-dev
        - libxpm-dev
        - libjpeg-dev
        - libtiff-dev
      become: yes
  
    - command: 'which evm'
      register: which_evm
      ignore_errors: yes
  
    - name: Install evm
      shell: 'curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash'
      when: which_evm|failed

    - name: mkdir /usr/local/evm
      file: path=/usr/local/evm state=directory owner={{ansible_user}}
      become: yes
  
    # for bash
    - stat: path={{BASHRC}}
      register: bashrc

    - name: Append 'PATH' to .bashrc
      lineinfile:
        dest={{BASHRC}}
        line='export PATH=$HOME/.evm/bin:$PATH'
        regexp='^export PATH=\$HOME/\.evm/bin'
      when: bashrc.stat.exists

    # for fish
    - stat: path={{CONFIG_FISH}}
      register: config_fish

    - name: Append 'PATH' to config.fish
      lineinfile:
        dest={{CONFIG_FISH}}
        line='set -x PATH $HOME/.evm/bin $PATH'
        regexp='^set -x PATH \$HOME/\.evm/bin'
      when: config_fish.stat.exists
