---
- name: Install Mill
  become: yes
  shell: "{{ item }}"
  with_items:
    - "curl -L -o /usr/local/bin/mill https://github.com/lihaoyi/mill/releases/download/{{ MILL_VERSION }}/{{ MILL_VERSION }}"
    - "chmod +x /usr/local/bin/mill"
