---
- name: Add the repository of sbt
  become: yes
  lineinfile:
    dest='/etc/apt/sources.list.d/sbt.list'
    line='deb https://dl.bintray.com/sbt/debian /'
    regexp='^deb https://dl\.bintray\.com/sbt/debian /'
    create=yes

- name: Download the key of trusted repository
  become: yes
  shell: 'apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823'

- name: Install sbt
  become: yes
  apt:
    name: sbt
    state: latest
    update_cache: yes
