---
- hosts: localhost

  vars:
    asset_name: "aws-vault-linux-amd64"

  tasks:
    - name: Fetch the latest release version from GitHub
      uri:
        url: https://api.github.com/repos/99designs/aws-vault/releases/latest
        body_format: json
      register: curl_result

    - set_fact:
        tarball_url: "{{curl_result|json_query(query)}}"
      vars:
        query: "json.assets[?name=='{{asset_name}}'].browser_download_url | [0]"

    - name: Download the binary
      become: yes
      get_url:
        url: "{{tarball_url}}"
        dest: /usr/local/bin/aws-vault
        mode: "a+x"
