---
- hosts: localhost

  vars:
    BASHRC: "{{HOME_DIR}}/.bashrc"
  
  tasks:
  
    # for bash
    - name: Get status .bashrc
      stat: path={{BASHRC}}
      register: bashrc

    - name: Add 'CONSCRIPT_HOME' to .bashrc
      lineinfile:
        dest={{BASHRC}}
        line='export CONSCRIPT_HOME=$HOME/.conscript/'
        regexp='^export CONSCRIPT_HOME'
      when: bashrc.stat.exists  
    
    - name: Append 'PATH' to .bashrc
      lineinfile:
        dest={{BASHRC}}
        line='export PATH=$CONSCRIPT_HOME/bin:$PATH'
        regexp='^export PATH=\$CONSCRIPT_HOME/bin'
      when: bashrc.stat.exists

    # for fish
    - name: Add the 'CONSCRIPT_HOME' universal variable for fish
      shell: 'set -U CONSCRIPT_HOME $HOME/.conscript/'
      args:
        executable: /usr/bin/fish
      
    - name: Append to the 'PATH' for fish
      shell: 'set -U fish_user_paths $CONSCRIPT_HOME/bin fish_user_paths'
      args:
        executable: /usr/bin/fish

    # Install conscript
    - name: which conscript
      command: 'which cs'
      register: which_cs
      ignore_errors: yes
  
    - name: Get setup script
      get_url:
        url: https://raw.githubusercontent.com/foundweekends/conscript/master/setup.sh
        dest: /tmp/setup.sh
        force: yes
        mode: u+x
      when: which_cs|failed

    - name: Install conscript
      shell: /tmp/setup.sh
      when: which_cs|failed
      ignore_errors: yes

