---
- hosts: ubuntu
  tasks:
    - name: Install pip
      become: yes
      apt:
        name: python-pip
        state: latest

    - name: Install pexpect
      become: yes
      shell: pip install pexpect

    - name: Download the deb file
      get_url:
        url: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb
        dest: /tmp/dropbox.deb

    - name: Install Dropbox
      become: yes
      apt:
        deb: /tmp/dropbox.deb

    - name: Install Dropbox Daemon
      become: yes
      expect:
        command: /usr/bin/dropbox start -i
        responses:
          'Note: python-gpgme is not installed': "y"
