---
- hosts: localhost

  
  tasks:

    - name: Remove the .emacs.d directory
      file: path="{{ ansible_env.HOME }}/.emacs.d" state=absent

    - name: Checkout config files from github
      git:
        repo: git@github.com:NomadBlacky/.emacs.d.git
        dest: "{{ ansible_env.HOME }}/.emacs.d"
        accept_hostkey: yes
        key_file: "{{ ansible_env.HOME }}/.ssh/id_rsa"
