---
- hosts: localhost

  
  tasks:

    - command: "which omf"
      register: omf_result
      ignore_errors: True

    - name: Download script that install omf
      get_url:
        url: http://get.oh-my.fish
        dest: "{{ansible_env.HOME}}/install_omf.fish"

    - name: Install oh-my-fish
      shell: "cat {{ansible_env.HOME}}/install_omf.fish | fish"
      when: omf_result|failed
    
    - name: Install 'cd' plugin
      shell: "fish -c 'omf install cd'"

    - name: Install 'peco' plugin
      shell: "fish -c 'omf install peco'"
      
