---
- hosts: localhost

  vars:
    BASHRC: "{{ansible_env.HOME}}/.bashrc"
    CONFIG_FISH: "{{ansible_env.HOME}}/.config/fish/config.fish"
  
  tasks:
    - name: Git clone 'pyenv-virtualenv'
      git:
        repo=https://github.com/yyuu/pyenv-virtualenv.git
        dest={{ansible_env.HOME}}/.pyenv/plugins/pyenv-virtualenv
        version=master

    # for bash
    - stat: path={{BASHRC}}
      register: bashrc

    - name: Add init virtualenv to .bashrc
      lineinfile:
        dest={{BASHRC}}
        line='eval "$(pyenv virtualenv-init -)"'
        regexp='^eval "\$\(pyenv virtualenv-init -\)"'
      when: bashrc.stat.exists
      
        
    # for fish
    - stat: path={{CONFIG_FISH}}
      register: config_fish

    - name: Add init virtualenv to config.fish
      lineinfile:
        dest={{CONFIG_FISH}}
        line='. (pyenv virtualenv-init - | psub)'
        regexp='^\. \(pyenv virtualenv-init - \| psub\)'
      when: config_fish.stat.exists
    
