---
- hosts: localhost

  vars:
    TMUX_CONFIG_FILE: "{{ansible_env.HOME}}/.tmux.conf"
  
  tasks:
    - name: Install tmux
      apt:
        name: tmux
        state: latest
      become: yes

    - name: Configure tmux file
      lineinfile:
        dest="{{TMUX_CONFIG_FILE}}"
        line="{{item.line}}"
        regexp="{{item.regexp}}"
        create=yes
      with_items:
        - { line: 'set -g prefix C-z'                               , regexp: 'set\s+-g\s+prefix'                }
        - { line: 'unbind C-b'                                      , regexp: 'unbind\s+C-b'                     }
        - { line: 'unbind -t emacs-copy M-w'                        , regexp: 'unbind\s+-t\s+emacs-copy\s+M-w'   }
        - { line: 'unbind -t emacs-copy C-w'                        , regexp: 'unbind\s+-t\s+emacs-copy\s+C-w'   }
        - { line: 'bind-key -t emacs-copy M-w copy-pipe "xsel -bi"' , regexp: 'bind-key\s+-t\s+emacs-copy\s+M-w' }
        - { line: 'bind-key -t emacs-copy C-w copy-pipe "xsel -bi"' , regexp: 'bind-key\s+-t\s+emacs-copy\s+C-w' }
