---
- name: Install Ammonite
  become: yes
  get_url:
    url: "https://github.com/lihaoyi/Ammonite/releases/download/{{ AMMONITE_VERSION }}/{{ SCALA_VERSION }}-{{ AMMONITE_VERSION }}"
    dest: /usr/local/bin/amm
    mode: +x
    force: yes
